### ISSUE TITLE
Release 1.2.2

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Achilles#117]
This is the tracking issue for 1.2.2.

- [x] Cofirm bugfixes for release
- [x] Create release notes
- [x] Publish Release
- [x] Announce on OHDSI forums
