### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Achilles#128]
This is the tracking issue for 1.2.2.

- [x] Cofirm bugfixes for release
- [x] Create release notes
- [x] Publish Release
- [x] Announce on OHDSI forums

**Comment by vojtechhuser** [comment]
Forum post is done
I marked one issue with 1.3.0 tag.
All new features are only partially addressing the other "running issues" - so they are referenced but not closed.
