### ISSUE TITLE
Achilles Release 1.5.0

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Achilles#226]
### Release Version V1.5.0
- [x] Create Release Notes
- [x] Obtain sign off
- [x] Publish Release
- [x] Communicate production change to team
- [x] Communicate release via OHDSI forums

**Comment by chrisknoll** [comment]
@t-abdul-basser , @vojtechhuser,
  I've copied and modified a template we use to release WebAPI from the other repo.  We'd like to know if either of you are managing releases going forward, and if so, we'd like to have a 1.5.0 release soon because of dependencies on Atlas and WebAPI.  If you are managing releases going forward, please take care in creating proper release notes when you draft the release (via the github release process) and follow the tagging format (v1.5.0 for example).  

Let us know if you can manage these releases or if someone else needs to step in.

**Comment by vojtechhuser** [comment]
I am happy to help with drafting the release notes. My Achilles role is helping review changes. I am not that good with git to be able to help with travisCI testing. (Taha I think has access).I would be eager to learn those steps from experts though.

**Comment by t-abdul-basser** [comment]
@chrisknoll Thanks for the checklist template. Yes, we would love to handle releases going forward. I still have at least one more PR that needs to be processed and then we can agree on a release date. Given other commitments, I would estimate that it will be early next week at earliest. Please let us know if this is work for you and the WebAPI and Atlas release planning.
@vojtechhuser  If you could draft release notes that would be great!

**Comment by chrisknoll** [comment]
I think waiting for next week at the earliest is a bit too far out to have the other constraints of the release for the OHDSI symposium. So I would appreciate it if you would take the current master branch with it's changes since last release, and make a release as soon as possible, and then feel free to do a 1.5.1 release shortly after if you have something else you'd like to get out in the release.

**Comment by chrisknoll** [comment]
@vojtechhuser ,
 I saw that you started the release for 1.5.0, Thank you for that.  Here's a link that will show you the commits to master from 1.4.0 to current master:
https://github.com/OHDSI/Achilles/compare/1.4.0...master

I don't think you need to call out changes like the issue reporting template update, but things like handling the CDM Meta table, the changes you made, the new DataConnector updates, Frequenency Distribution report, etc would be good bullets.  The release notes don't have to be very detailed, but definitely call out those thing that the users of the library should probably know about that has changed since the last release.

**Comment by vojtechhuser** [comment]
I created draft of release notes.
I made a PR for changing the version to 1.5 (so Taha may possibly merge)

**Comment by chrisknoll** [comment]
Hi, I believe myself, @anthonysena and @alondhe can give signoff from our side.  If you guys are good with that, you can tick off the 'signoff' checkbox. From our perspective, the 1.5 release has everything we need for the external dependencies for the other release artifacts for the October OHDSI software release (WebAPI/ Atlas, SqlRender, etc).  So if you have any more things you'd  like to add to this release, please try to get that completed within the next few days, otherwise please consider pushing it out to a 1.6 release.

Thank you!

-Chris

**Comment by anthonysena** [comment]
Agreed - thanks @chrisknoll. I've started to reference V1.5 of Achilles in the WebAPI/Atlas release notes and plan to release that in the next day or so.

**Comment by t-abdul-basser** [comment]
Excellent. Sorry for the day: I meant to finish this Friday. I will release today.

**Comment by anthonysena** [comment]
Thanks @t-abdul-basser!

**Comment by chrisknoll** [comment]
@t-abdul-basser , will you be making the 1.5 release today?

**Comment by t-abdul-basser** [comment]
Yes. Sorry I was out sick but will release today.

**Comment by t-abdul-basser** [comment]
Released.

**Comment by chrisknoll** [comment]
Thank you, @t-abdul-basser and @vojtechhuser !

**Comment by anthonysena** [comment]
Thanks everyone!
